### ListContries
GET http://localhost:8080/api/v1/countries
Accept: application/json

### CountryById
@countryId = 3
GET http://localhost:8080/api/v1/countries/{{countryId}}

###
POST http://localhost:8080/api/v1/countries
Content-Type: application/json

###
PUT http://localhost:8080/api/v1/countries/{{countryId}}

###
DELETE http://localhost:8080/api/v1/countries/{{countryId}}




